65130
WPDevelopers/essential-addons-for-elementor-lite pull request #774
Opened 2024-10-03 06:41 UTC by jakaria-istauk

2024-10-03 12:57 UTC, robinwpdeveloper reviewed
Left minor feedbacks @himadree bhai

2024-10-03 12:57 UTC, robinwpdeveloper commented on includes/Elements/Team_Member.php
> +		$team_member_image = $settings['eael_team_member_image'];
Even though we have this value all the time, but doing empty check will be good too.
```
$team_member_image = $settings['eael_team_member_image'] ?? '';
```

2024-10-03 12:57 UTC, robinwpdeveloper commented on includes/Elements/Team_Member.php
> +			$team_member_image_url = $team_member_image['url'];
Also empty check here (although we are getting this value all the time possibly):
```
$team_member_image_url = $team_member_image['url'] ?? '';
```

2024-10-08 10:25 UTC, himadree commented
Updated all feedbacks

2024-10-14 10:16 UTC, robinwpdeveloper requested changes
Left minor feedback

2024-10-14 10:16 UTC, robinwpdeveloper commented on includes/Elements/Team_Member.php
> +		$team_member_image = $settings['eael_team_member_image'] ?? null;
@himadree bhai let's use `''` instead of null (in both places)
We have 0 occurrences of null in php files. 
We are mostly using `''`

2024-10-16 10:43 UTC, himadree commented
Update feedback

2024-10-16 11:23 UTC, merged