66343
WPDevelopers/essential-addons-for-elementor-lite pull request #776
Opened 2024-10-10 05:26 UTC by jakaria-istauk

2024-10-21 12:35 UTC, robinwpdeveloper requested changes
Left few feedbacks.
Mostly spacing related.

2024-10-21 12:35 UTC, robinwpdeveloper commented on includes/Template/Eicon-Woocommerce/preset-2.php
> +$sale_badge_text = !empty($settings['eael_product_sale_text']) ? $settings['eael_product_sale_text'] :  __( 'Sale!', 'essential-addons-for-elementor-lite' );
`! empty` on all occurances

2024-10-21 12:35 UTC, robinwpdeveloper commented on includes/Template/Eicon-Woocommerce/preset-2.php
> +$stock_out_badge_text = !empty($settings['eael_product_stockout_text']) ?$settings['eael_product_stockout_text'] : __( 'Stock <br/> Out', 'essential-addons-for-elementor-lite' );
1 space before and after ternary operator (?).

2024-10-21 12:35 UTC, robinwpdeveloper commented on includes/Template/Eicon-Woocommerce/preset-2.php
> +                    if( $should_print_image_clickable ) {
`if () {}` on all occurances

2024-10-24 05:47 UTC, jakaria-istauk commented on includes/Template/Eicon-Woocommerce/default.php
> +if($settings['eael_product_grid_rating']!='yes'){
yes

2024-10-24 05:52 UTC, jakaria-istauk commented on includes/Template/Eicon-Woocommerce/default.php
> +		echo '<span class="outofstock-badge">'. $stock_out_badge_text .'</span>';
Although this is a default template and value can changed by user via using hook, if we use escaping it's may causing of design break.

2024-10-24 05:55 UTC, jakaria-istauk commented on includes/Template/Eicon-Woocommerce/default.php
> +add_action('woocommerce_before_shop_loop_item_title',function() use ( $stock_out_badge_text ){
Although this is a default template and value can changed by user via using hook, if we use escaping it's may causing of design break.

2024-10-24 05:56 UTC, jakaria-istauk commented on includes/Template/Eicon-Woocommerce/default.php
> +	return '<span class="onsale" data-notification="default">'. $sale_badge_text .'</span>';
Although this is a default template and value can changed by user via using hook, if we use escaping it's may causing of design break.

2024-10-27 09:33 UTC, robinwpdeveloper approved these changes

2024-10-28 04:59 UTC, merged