71535
WPDevelopers/essential-addons-for-elementor-lite pull request #778
Opened 2024-10-21 10:46 UTC by himadree

2024-10-21 11:04 UTC, robinwpdeveloper approved these changes

2024-10-21 11:12 UTC, robinwpdeveloper requested changes
`essential-addons-elementor` textdomain found on 
- Woo Product Carousel
- Traits/Controls.php

2024-10-29 05:37 UTC, himadree commented
Feedback Done

2024-10-29 05:54 UTC, robinwpdeveloper approved these changes

2024-10-29 06:25 UTC, merged